### ISSUE TITLE
Basic Website Design

### ISSUE THREAD

**Issue by captainalan** [kaiwahour/home#1]
- [x] What pages/routes are needed?
- [x] Code basic routing
- [ ] Design sketch/prototype

**Comment by captainalan** [comment]
@gabriellaquattrone is working on the initial prototype in Adobe Xd

**Comment by captainalan** [comment]
The following pages/routes will be needed:

- Home
    - Normal meeting times
    - Upcoming events
    - Other news
- FAQ
    - e.g. "do I have to already speak Japanese fluently to join?
- About
    - message from founders, history of the org, etc.
- Contributing
    - Info on how people can contribute

This app will be a single page application (SPA) but it will act like a multi-paged "normal" website.

These items will be in a footer:

- Contact info
- Social media links

**Comment by gabriellaquattrone** [comment]
Since you already started working on the website (and it looks great!) I really think there is no need for me to finish my prototype now.

**Comment by captainalan** [comment]
@gabriellaquattrone do you want to get us a working image carousel with the pics you found? I'll close this issue but we need more help on many others!
