### ISSUE TITLE
Make the footer look nice, complete with social media links

### ISSUE THREAD

**Issue by captainalan** [kaiwahour/home#19]
On this [UC Davis Website](https://www.comfort.ucdavis.edu/morning-ac) the footer looks nice; incorporate some of these design ideas:

-  Bolded footing headers, different colors
    - All caps geometric font looks nice
- Finish social media integration—look for React components for
    - Facebook
    - Discord
    - (The Twitter one seems to be working well)
- Copyright stuff quietly chilling at the bottom
    - Use less vertical space than the UCD site between

**Comment by gabriellaquattrone** [comment]
I made a new footer branch and started on the design. Let me know how it looks!

**Comment by captainalan** [comment]
Good work; we can close this issue for now since we did the major design reworks. We'll tweak the text as necessary as we get more information.
