### ISSUE TITLE
Fix extra whitespace showing on side

### ISSUE THREAD

**Issue by gabriellaquattrone** [kaiwahour/home#23]
![](https://cdn.discordapp.com/attachments/429345493018214406/579023197328900125/Screen_Shot_2019-05-17_at_12.10.43_PM.png)

Here is a screenshot showing the issue. Not sure where it's coming from.

**Comment by captainalan** [comment]
I got this on mobile (but not on desktop), and the page loads nicely by default.

It is only when I try to scroll right/left that the screen can shift a bit. Can you describe where this issues came up for you a bit? @gabriellaquattrone

**Comment by gabriellaquattrone** [comment]
This comes up for me on desktop, when I scroll right/left as well. I'm using Chrome.

**Comment by captainalan** [comment]
@gabriellaquattrone 
oh snap! it does for me too; i just failed at trying to scroll left/right earlier; okay we'll keep on searching for the cause of this :/

**Comment by captainalan** [comment]
Thanks for pointing out this error @gabriellaquattrone 
we should be good now
https://github.com/kaiwahour/home/commit/190d93773ad4b960e91b079e23b14473ba046e1a
