### ISSUE TITLE
Gather website text (from social media, etc.)

### ISSUE THREAD

**Issue by captainalan** [kaiwahour/home#3]
Gather text we already have written elsewhere (e.g. Facebook, Twitter, etc.) to post to the new Kaiwa Hour (official) website.

Create appropriate Wiki page(s).

**Comment by tkiapril** [comment]
I can code for Twitter crawlers, Facebook maybe also.

**Comment by captainalan** [comment]
This may be a good idea for aggregating news stories, finding Japan-related stuff to interact with, and more; I've created a new repo we can add web scraping type stuff too as we build things.

https://github.com/kaiwahour/mushi

**Comment by gabriellaquattrone** [comment]
Could you comment about why you closed it? @captainalan

**Comment by captainalan** [comment]
I grabbed with "About" text from FB already; we'll need to write up the FAQ and other pages from scratch
