### ISSUE TITLE
Needed: Nice looking photographs for use on Kaiwa site

### ISSUE THREAD

**Issue by captainalan** [kaiwahour/home#5]
Got nice pictures of Japan(ese) related stuff? Have your photography/artwork featured here.

A nice way to contribute for the artistically inclined.

**Comment by gabriellaquattrone** [comment]
![Flowers in Kyoto Garden](https://user-images.githubusercontent.com/30669574/57891710-36b27700-77f1-11e9-9b35-8a58f813f158.jpg) Flowers in Kyoto Garden

![A Shinto or Buddhist Meal](https://user-images.githubusercontent.com/30669574/57891811-9f015880-77f1-11e9-896e-fa73449214fc.jpg) A Shinto or Buddhist Meal

![IMG_2486](https://user-images.githubusercontent.com/30669574/57891860-c5bf8f00-77f1-11e9-9601-4a7d872f9b72.jpg) Arashiyama Monkey

![buddha](https://user-images.githubusercontent.com/30669574/57891924-03241c80-77f2-11e9-9e10-7884d652cf76.jpg) Buddha

![cat](https://user-images.githubusercontent.com/30669574/57891945-10d9a200-77f2-11e9-9f4b-ed2b84dc0520.jpg) At Cat Cafe
![IMG_5678](https://user-images.githubusercontent.com/30669574/57892014-59915b00-77f2-11e9-890f-6129458b7653.jpg) Japanese Tea

**Comment by captainalan** [comment]
These look good—I'll make a Wiki page with link to Japan-related pics we can use as needed 👍

**Comment by captainalan** [comment]
infos added to wikihttps://github.com/kaiwahour/home/wiki/Images
