### ISSUE TITLE
Find hosting for images used on this site

### ISSUE THREAD

**Issue by captainalan** [kaiwahour/home#6]
Images hosted in the `public` folder during development display properly on the development server, but are not automatically packages up and exported using build scripts.

Rather than fiddling with these complicated things, why not find somewhere (external) that will allow linking images?

**Comment by tkiapril** [comment]
imgur?

**Comment by captainalan** [comment]
Imgur looks good for trending/shared images; we may to find somewhere else to put things like event photos or that sort of thing

**Comment by tkiapril** [comment]
Yup, it's quite easy to upload to and embed stuff from imgur so it might be good for linking public stuff. For private stuff, I don't know, maybe we can use image services like flickr that supports widgets (I think flickr may support direct embedding as well.)

**Comment by captainalan** [comment]
Hosting discussions being moved to the [Wiki](https://github.com/kaiwahour/home/wiki/Hosting).
